### ISSUE TITLE
Failed to create an instance of 'com.github.gwtbootstrap.client.ui.TabPanel' via deferred binding

### ISSUE THREAD

**Issue by phlukman** [gwtbootstrap/gwt-bootstrap#501]
Hi guys

I'm using version 2.2.1.0 of your API, along with GWT 2.5.1 and GWTP 1.0 and I'm having an exception being thrown whenever I try to use the TabPanel widget. This does not happen when using other Bootstrap widgets...
Do you know why?

This is the stactrace:

com.google.gwt.core.client.JavaScriptException: (TypeError) @com.github.gwtbootstrap.client.ui.TabPanel::setHandlerFunctions(Lcom/google/gwt/dom/client/Element;)([JavaScript object(123)]): undefined is not a function    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:249)    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:571)  at com.google.gwt.dev.shell.ModuleSpace.invokeNativeVoid(ModuleSpace.java:299)  at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeVoid(JavaScriptHost.java:107)    at com.github.gwtbootstrap.client.ui.TabPanel.setHandlerFunctions(TabPanel.java)    at com.github.gwtbootstrap.client.ui.TabPanel.<init>(TabPanel.java:223)     at com.github.gwtbootstrap.client.ui.TabPanel.<init>(TabPanel.java:205)     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)     at java.lang.reflect.Constructor.newInstance(Constructor.java:513)  at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:475)   at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:49)     at com.google.gwt.core.shared.GWT.create(GWT.java:57)   at com.google.gwt.core.client.GWT.create(GWT.java:85)   at com.touchtunes.cportal.client.application.home.popups.LiveRoutePopupViewImpl_BinderImpl$Widgets.build_tabPanel(LiveRoutePopupViewImpl_BinderImpl.java:181)

**Comment by rkfg** [comment]
For anyone coming here from Google: this may happen if you put the ```<entry-point>``` tag in your Module.gwt.xml above the ```<inherits>``` tag for GWT Bootstrap. Just happened to me. The ```<entry-point>``` tag should be placed **after** all the ```<inherits>``` tags.
